require("plugins")
require("options")
require("mappings")

-- Plugins configuration
require("config.treesitter")
require("config.nvim-lspconfig")
require("config.fidget")
require("config.trouble")
require("config.nvim-cmp")
require("config.null-ls")
require("config.dap")
require("config.telescope")
require("config.gitsigns")
require("config.lualine")
require("config.neogen")
require("config.comment")
require("config.autopairs")
require("config.autotag")
require("config.indent")
require("config.dressing")
require("config.rust-tools")
require("config.diffview")
require("config.neogit")
