alias py="~/.workdir/.venv/bin/ipython"
alias redis-cli="docker run --network=host --name redis-cli -it --rm redis redis-cli"
alias mongo="docker run --network=host --name mongo-cli -it --rm mongo mongo"
alias dockershell="docker run --rm -it --entrypoint=/bin/bash"
alias dockershellsh="docker run --rm -it --entrypoint=/bin/sh"
alias v="nvim"
alias vim="nvim"
alias cd="z"
alias docker-compose="docker compose"
alias yarn="corepack yarn"
