[scripts.update]
command = "sudo apt-get update -y && sudo apt-get upgrade -y"
alias = "update"
description = "Update packages"
tags = ["apt"]

[scripts.git-flush]
command = '''
#!/usr/bin/zsh

git fetch -p
for branch in $(git for-each-ref --format '%(refname) %(upstream:track)' refs/heads | awk '$2 == "[gone]" {sub("refs/heads/", "", $1); print $1}')
do
		git branch -D $branch
done
'''
alias = "git-flush"
description = "Delete Git branches gone on remote"
tags = ["git"]

[scripts.vpn-up]
command = 'nmcli con up isec'
alias = "vpn-up"
description = "Connect to VPN"
tags = ["network"]

[scripts.vpn-down]
command = 'nmcli con down isec'
alias = "vpn-down"
description = "Disconnect VPN"
tags = ["network"]

[scripts.check-ssh-certs]
command = '''
#!/usr/bin/zsh

autoload colors; colors
red=${fg[red]}
yellow=${fg[yellow]}
green=${fg[green]}

# warn is a number of days for yellow/green color selection
warn=15

# default number of days to show set to a big value or first argument
days=${1:-$((0xffffffff))}

printed=0
for i in ~/.ssh/*-cert.pub; do 
	exptz=$(ssh-keygen -L -f $i| awk '/Valid: /{ print $5 }')
	expunix=$(date -u  -d "${exptz}" +%s)
	explocf=$(date -u  -d "${exptz}")
	nowunix=$(date +%s)
	
	remdays=$((($expunix - $nowunix)/(3600*24)))

	# choose color depending of remaining time
	[ $remdays -gt ${warn} ] && color=${green}
	[ $remdays -gt 0  ] && [ $remdays -le ${warn} ] && color=${yellow}
	[ $remdays -le 0 ] && color=${red}

	if [ $remdays -lt ${days} ] && [ $remdays -ge 0 ]; then
		echo -e "$(basename $i) expires on ${explocf}, ${color}${remdays} days left${reset_color}"
		printed=1
	fi
	if [ $remdays -lt 0 ]; then
		echo -e "$(basename $i) expired on ${explocf}, ${color}$((-1 * ${remdays})) days ago${reset_color}"
		printed=1
	fi
done
[ ${printed} -eq 1 ] && echo ""
return 0
'''
alias = "check-ssh-certs"
description = "Check ssh certificates expiration dates"
tags = ["network"]

[scripts.blacklist-ip]
command = '''
#!/usr/bin/python3

import pymongo
import sys

client = pymongo.MongoClient("mongodb.footprint")
col = client.footprint.assets


def blacklist(ip):
    doc = col.find_one_and_update(
        {"name": ip},
        update={"$push": {"tags": "blacklisted"}},
        return_document=pymongo.collection.ReturnDocument.AFTER,
    )
    return doc


def is_blacklisted(ip):
    doc = col.find_one({"name": ip}, {"tags": 1})
    return "blacklisted" in doc.get("tags", [])


if __name__ == "__main__":
    ip = sys.argv[1]
    if is_blacklisted(ip):
        print(f"[-] {ip} is already blacklisted")
        exit(1)
    else:
        doc = blacklist(ip)
        print(f"[+] {ip} has been successfully blacklisted", doc)
'''
alias = "blacklist-ip"
description = "Blacklist an IP in ASM"
tags = ["asm"]
